#!/usr/bin/env bash
# generated by make-theme.cjs — plate reaction for theme "anchor-vertical"
set -euo pipefail
cd "$(dirname "$0")"
ffmpeg -y -v error -i final.mp4 -filter_complex "
  [0:v]scale=2160:3840:flags=lanczos,zoompan=z='1+0.012*time/35.88':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':d=1:s=2160x3840:fps=30,scale=1080:1920:flags=lanczos,
  noise=alls=5:allf=t+u[v]" \
  -map "[v]" -map 0:a -c:v libx264 -crf 14 -preset slow -profile:v high -c:a copy \
  final_fx.mp4
echo "[postfx] anchor-vertical → final_fx.mp4"
